services:
  ai-uc-rpa-guidance:
    build:
      target: development
      context: ../repos/ai-uc-rpa-guidance
    ports:
      - 8085:8085
    links:
      - "floci:floci"
      - "mongodb:mongodb"
    depends_on:
      floci:
        condition: service_healthy
      mongodb:
        condition: service_started
    env_file:
      - "../.env"
    environment:
      PORT: ${PORT:-8085}
      MONGO_URI: ${MONGO_URI:-mongodb://mongodb:27017/}
      HOST: ${HOST:-0.0.0.0}
      HOST_URL: ${HOST_URL:-http://host.docker.internal:8085}
      FLOCI_URL: ${FLOCI_URL:-http://floci:4566}
      S3_ENDPOINT: ${S3_ENDPOINT:-http://floci:4566}
      SQS_ENDPOINT: ${SQS_ENDPOINT:-http://floci:4566}
    volumes:
      - ../repos/ai-uc-rpa-guidance/app:/home/nonroot/app
    develop:
      watch:
        - action: rebuild
          path: ../repos/ai-uc-rpa-guidance/pyproject.toml
          target: /home/nonroot/pyproject.toml
    networks:
      - ai-uc-rpa-guidance
